### ISSUE TITLE
Model Error

### ISSUE THREAD

**Issue by ghost** [ManuelPalermo/X-Ray-ConvNet#4]
Hi, bro, have u test all the model? When I change the model to nasmobile, error occurs:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files (x86)\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files (x86)\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/DL/Main.py", line 58, in <module>
    n_classes=1).get_model()
  File "D:\DL\CNN_Model.py", line 11, in __init__
    self.model      = self.select_model(model2load, percent2retrain)
  File "D:\DL\CNN_Model.py", line 22, in select_model
    return self.nas_mobile_net(percent2retrain)
  File "D:\DL\CNN_Model.py", line 60, in nas_mobile_net
    include_top=False)
  File "D:\ProgramData\Anaconda3\envs\US\lib\site-packages\keras\applications\__init__.py", line 20, in wrapper
    return base_fun(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\US\lib\site-packages\keras\applications\nasnet.py", line 11, in NASNetMobile
    return nasnet.NASNetMobile(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\US\lib\site-packages\keras_applications\nasnet.py", line 433, in NASNetMobile
    **kwargs)
  File "D:\ProgramData\Anaconda3\envs\US\lib\site-packages\keras_applications\nasnet.py", line 168, in NASNet
    weights=weights)
  File "D:\ProgramData\Anaconda3\envs\US\lib\site-packages\keras_applications\imagenet_utils.py", line 292, in _obtain_input_shape
    str(default_shape) + '.')
ValueError: When setting `include_top=True` and loading `imagenet` weights, `input_shape` should be (224, 224, 3).

Do u have any idea about it?

**Comment by ManuelPalermo** [comment]
Hi, the pretrained models need a specific input shape if include_top=True, in the case of nasmobile its (224,224,3): https://keras.io/api/applications/nasnet/

You have two choices:
* change the input shape to (224,224,3) -> instead of the default (128,128,3)
* set include_top=False and add custom input layer with desired dimensions: model.add(*new_input_layer*) before adding the nas_mobile_model

**Comment by ghost** [comment]
Thanks, I will try it later, you may also modify your code on github when u are free.

**Comment by ManuelPalermo** [comment]
Try it and let me know if it solves the problem, also feel free to submit a pull request ;)

**Comment by ghost** [comment]
Hi, I am a bit confused about this:

don't execute all of them, as that would often be way too strong

This is your comment, but then it seems that you execute all, because:

data_loader = DataLoader(augment_data=True)

And nothing is commented in DatasetGenerator

**Comment by ManuelPalermo** [comment]
(Sorry, did not receive notification)

Yes, in the code I execute all. This was mostly a learning exercise for me, and now serves as an (outdated) example.
You should just select the augmentations you think make sense.
